#!/bin/bash
#$1 wallpaper dir
#$2 i3 config path
#$3 xresources path

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


./wallpaper_changer $1 $DIR

./color_determinator "$(cat $DIR/CURRENT_WALLPAPER)" "$DIR/config_blueprint" "$2" "$DIR/.Xresources_blueprint" "$3" "$DIR"